version: '3'
services:
  my-app:
    image: "my-app:1.0"
    ports:
     - 3000:3000
    container_name: "my-app-crud"
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin                
     - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: "my-mongodb"
  mongo-express:
    image: mongo-express
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin                
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: "my-mongo-express"